
CREATE TABLE USER (
      ID INT NOT NULL,
      USERNAME VARCHAR(256) NULL,
      PASSWORD VARCHAR(256) NULL,
      FIRSTNAME VARCHAR(256) NULL,
      LASTNAME VARCHAR(256) NULL,
      EMAIL VARCHAR(256) NULL,
      ROLE VARCHAR(100) NULL,
      custom_field_1 VARCHAR(256) NULL,
      custom_field_2 VARCHAR(256) NULL,
      custom_field_3 VARCHAR(256) NULL,
      custom_field_4 VARCHAR(256) NULL,
      ENABLED BOOL,
      LASTPASSWORDRESETDATE DATE
);

CREATE TABLE AUTHORITY (
    ID INT NOT NULL,
    NAME VARCHAR(256) NULL
);

CREATE TABLE USER_AUTHORITY (
     USER_ID INT NOT NULL,
     AUTHORITY_ID INT NOT NULL
);